// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar general que usa la estructura completa del directorio "Tutorial"
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'Tutorial' }],
  
  // Sidebar específico para desarrollo
  desarrolloSidebar: [
    {
      type: 'category',
      label: 'Agregar documentación',
      items: [ 
        'accesa-docs/desarrollo/formularioDesarrollo',
        'accesa-docs/desarrollo/subirArchivoDesarrollo'], 
    },
    {
      type: 'category',
      label: 'Dashboard',
      items: [ 
        'accesa-docs/desarrollo/Dashboard/dashboard-accesa',
        'accesa-docs/desarrollo/Dashboard/dashboard-process'], 
    },
    {
      type: 'category',
      label: 'Portal Accesa',
      items: [ 
        'accesa-docs/desarrollo/APInfancia'], 
    },
    {
      type: 'category',
      label: 'Gestión de Usuarios',
      items: [ 
        'accesa-docs/desarrollo/Gestion de Usuarios/user-management'], 
    },
    {
      type: 'category',
      label: 'New Portal',
      items: [ 
        'accesa-docs/desarrollo/APInfancia',
      'accesa-docs/desarrollo/NewPortal/performance-evaluation-backend'], 
    }
  ],
  
  // Sidebar específico para tecnología
  /*tecnologiaSidebar: [
    {
      type: 'category',
      label: 'Tecnología',
      items: ['accesa-docs/tecnologia/subirArchivoTecnologia', 'accesa-docs/tecnologia/1'], // Documento correcto dentro de tecnología
    },
  ],*/
};

export default sidebars;
