name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [ "desa" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use Node.js 18 here

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build    
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: accesa-desarrollo
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the accesadocs_front_desa Docker image
        run: |
            docker build . --tag ghcr.io/accesa-desarrollo/accesadocs_front_desa:latest
            docker push ghcr.io/accesa-desarrollo/accesadocs_front_desa:latest